### ISSUE TITLE
作者你好，提一些建议

### ISSUE THREAD

**Issue by typ0520** [hnsugar/android-debugdata-webtool#1]
- 提供一个给release依赖的包，只保留DebugDataTool(留一个initialize方法)和onDebugToolListener(完整)这两个类
- 加一个service在里面能开启socket监听，端口可以根据配置指定，如果没有指定从某个端口开始循环直到套接字创建完成
- 在文件管理里中对一些扩展名的文件做删除、修改、展示的操作(比如xml、sqlite、json、txt、dex等等)，如果某些扩展名的文件没有处理器就按文本或者二进制文件处理，这样管理页面上完全可以去掉数据库和共享参数这两个tab，
- 可以再加一个对/sdcard目录的展示，这块代码都有了就是换个根目录进行读取而已

**Comment by hnsugar** [comment]
建议不错，我回答一下问题
1.release包大部分是要发版的，提供后台是不安全的。当然也有release包测试情况，使用者可以自己控制在release环境编译,将 debugImplementation换成 Implementation 就可以在release包用了。
自动启动服务和手动启动是不冲突的，手动启动服务优先自动，即使服务已启动也会关闭旧的服务按新配置运行。
2.socket监听用服务和不用区别不太大，主要是工具定位决定的，测试时app正常运行socket也是正常工作的，防止被杀保活意义不大。
默认8088端口，手动启动可以指定端口号等，自动启动使用Provider被系统自动加载方案，Json工具类使用反射方法找到使用者使用的第三方工具，使用默认端口，https://github.com/amitshekhariitbhu/Android-Debug-Database 这位作者就是自动启动方案，通过build.gradle配置端口号，我写这个项目本意是辅助开发和测试，为了减少对使用者项目影响，所以不打算用配置文件方式设置端口。
3.这条建议是可行的，但是开发难度上升了，分tab是为了更快的对对应数据进行操作，大部分数据库和xml存储位置符合android目录规范，如果搞特殊化可以通过文件管理下载到电脑进行操作，如果你感兴趣，可以与我交流，如果可以你可以自己实现，我很懒。
4.sdcard目录我不考虑的原因很简单，sd卡是开放的，data目录是不开放的，android studio3.0以前是不能读的，3.0开始可以debug文件目录，所以文件管理功能在某些情况下有了替代品，但是还是比android studio方便点，还有就是，sdcard目录下某些文件太大，服务写的没那么强壮，会崩溃的。

**Comment by typ0520** [comment]
关于第一条我的意思是如果只有debug的包依赖了debugdata-webtool,release的包，在Applciation初始化的时候没有对应的类对报错的，可以提供一个release依赖的包只有初始化相关的api，其它的都移除，里面可以什么逻辑都没有

**Comment by hnsugar** [comment]
晓得了，我没想到
